spring.application.name=backend

# ===============================
# PostgreSQL DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:postgresql://ep-sparkling-river-aq46l7ym.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.username=neondb_owner

spring.datasource.password=npg_InSyXOiW5p4v

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================

server.port=8080

# Actuator / Micrometer
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Logging
logging.level.com.travel=INFO
logging.level.org.springframework=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
